### ISSUE TITLE
Scope with multiple permissions asked for - no escape needed for separator char "+" and for permissions names

### ISSUE THREAD

**Issue by coronag** [aminjam/Aminjam.Owin.Security#2]
Seems like when having multiple permissions asked for ... this is not working.
For instance if my scope contains "likes" and "public_content" ... then the response is :
{
code: 400,
error_type: "OAuthException",
error_message: "Invalid scope field(s): likes+public_content"
}

But I managed to have a working url by changing this in my browser :
&scope=likes%2Bpublic_content
with this:
&scope=likes+public_content

So you may change that part in the (...)AuthHandler.cs file :
"&scope=" + Uri.EscapeDataString(scope)
=> ... which must be :
  "&scope=" + scope

**Comment by aminjam** [comment]
Merged https://github.com/aminjam/Aminjam.Owin.Security/pull/3

**Comment by aminjam** [comment]
@coronag Updated the nuget pacakge, let me know if you run into other issues. https://www.nuget.org/packages/Aminjam.Owin.Security.Instagram/0.0.3

**Comment by coronag** [comment]
thanks
